### ISSUE TITLE
[bug] no audio output (recipient of call can't hear me) using v1.2.8 on mac book pro m1

### ISSUE THREAD

**Issue by arooni** [jerrod-lankford/google-voice-desktop-app#101]
I have verified at voice.google.com I can place outgoing calls and the recipient of those phone calls can hear me.  However, on this app, even with the same settings for the microphone, the recipient cannot hear me.

**Comment by arooni** [comment]
this link was also helpful 

https://howto.salesflare.com/en/articles/1016951-how-can-i-change-the-default-calling-app-on-a-mac#:~:text=To%20change%20the%20default%20calling,for%20calls%20to%20%22FaceTime%22.&text=You%20have%20to%20change%20the%20%22tel%3A%22%20handler.

**Comment by akanter** [comment]
Yeah I've been having this same problem too on Monterey 12.1-2. I *think* it might have something to do with the app not requesting microphone access under Preferences -> Security & Privacy -> Microphone.

There's no way to manually add it either AFAICT.

**Comment by yuranlu** [comment]
I'm running into the same problem on a Macbook Pro M1 running Monterey 12.1, and v1.2.8 of this app.  It doesn't seem to pick up any of my microphone input when I'm on a call (using the default microphone on the computer).

**Comment by justdave** [comment]
See also #106 which seems to have some workarounds on it.
