### ISSUE TITLE
observation re: stability

### ISSUE THREAD

**Issue by dave15559546** [jerrod-lankford/google-voice-desktop-app#102]
fyi I used to have the app crash 1-2x/day until I transferred my google voice number to a new google account (I only did so because I don't want to pay for google workspace soon and it's unclear if one can transfer google voice numbers starting soon) so now the application takes up much less memory and is more reliable  (I only have a few short conversations on it at the moment)

note that I had archived many of my conversations in google voice but many of the residual ones had giant histories I suspect that somehow took up memory

probably nothing that jerrod can do about this given that this is just an electron app but maybe not?

of note, my ios google voice app works much better now since it seemingly was similarly deficient in being very slow due to 10+ years of history linked to the account (despite archiving many of the conversations)

**Comment by jerrod-lankford** [comment]
Thanks for the information!
