### ISSUE TITLE
1.2.9 JavaScript startup crash

### ISSUE THREAD

**Issue by rpodric** [jerrod-lankford/google-voice-desktop-app#115]
On Win11 (22000.652), that version doesn't run for me. It crashes upon startup and then hangs in memory.

https://i.imgur.com/svm3dAF.png

Reverting to 1.2.8 is fine. If there's anything you want me to try, like deleting its profile dir (thereby resetting it), just let me know.

Thanks

**Comment by RandomNerd1** [comment]
+1, also reverted to 1.2.8 to 'fix' it

**Comment by jerrod-lankford** [comment]
My bad, thats what i get for not testing PR's. Fixed by [e2a4e01](https://github.com/jerrod-lankford/google-voice-desktop-app/commit/e2a4e0123176eb0013307a811f3dbbe7b93214e4) and release 1.3.0
