### ISSUE TITLE
White Keypad and Text Input Box in all Dark Modes - macOS

### ISSUE THREAD

**Issue by cyberfunk** [jerrod-lankford/google-voice-desktop-app#118]
Is it possible to theme the Keypad and Text input box to match the dark theme? In macOS the keypad and text entry box are a blinding white against the otherwise dark backdrop.
![1](https://user-images.githubusercontent.com/12664589/171961069-8cf77bdf-1267-440c-b705-d23dffb7ca62.png)

**Comment by cyberfunk** [comment]
End result
![2](https://user-images.githubusercontent.com/12664589/171962809-cada0f91-9878-4b24-9ad5-925ca04a8f52.png)

**Comment by stevario** [comment]
I would love to see some updates to the dark themes.  The white background with white font does make it very difficult to see the number that has been entered.  This is what it looks like as you type the number.

![image](https://user-images.githubusercontent.com/65557834/173689694-0f996439-10bf-4730-9bab-88aba2ed1b3e.png)

This is what it looks like if you select the number after you have typed it into the text field.

![image](https://user-images.githubusercontent.com/65557834/173689805-ec7fa024-30b5-42f7-9183-68f718de19bf.png)

I know the user cyberfunk was able to modify the CSS to make the background dark.  I do not really know how to do that.  In the best case... a new release would simply fix the dark themes.

Thanks!

**Comment by cyberfunk** [comment]
Btw my changes are not permanent. There are User CSS plug-ins for Chrome and Brave browser that would allow you to make changes but they do not work with this standalone app unfortunately. Only the developer can make the changes permanent in an updated release as @steveario requested.

**Comment by blooalien** [comment]
This same exact issue also exists in the Linux AppImage release as well.  I'd be more than willing to fork this and submit a pull request for the fix if anyone wants to turn me on to which specific file I'd enter those CSS changes listed above into.

**Comment by cyberfunk** [comment]
> This same exact issue also exists in the Linux AppImage release as well. I'd be more than willing to fork this and submit a pull request for the fix if anyone wants to turn me on to which specific file I'd enter those CSS changes listed above into. In the meantime, I'ma clone the repo and see if I can find it myself.
> 
> Edit: Aighty. Found where to edit the themes. I'ma see what I can do about gettin' a pull request together for this one.

Where did you find the themes? I'm using macOS.

**Comment by blooalien** [comment]
> > This same exact issue also exists in the Linux AppImage release as well. I'd be more than willing to fork this and submit a pull request for the fix if anyone wants to turn me on to which specific file I'd enter those CSS changes listed above into. In the meantime, I'ma clone the repo and see if I can find it myself.
> > Edit: Aighty. Found where to edit the themes. I'ma see what I can do about gettin' a pull request together for this one.
> 
> Where did you find the themes? I'm using macOS.

If you clone the repository and look in the root folder of the project, you'll find a file named `THEMES.md` that explains the theme stuff.  It should make sense to anyone who's familiar with typical modern web design methods involving SCSS/SASS/yarn stuff.  I'm still exploring, but I think I can get a proper patch set / pull request thrown together for this using your colors from above as a baseline starting point.  I'll just adapt that to the other dark themes by eyedroppering colors out of those other themes.

**Comment by cyberfunk** [comment]
> > > This same exact issue also exists in the Linux AppImage release as well. I'd be more than willing to fork this and submit a pull request for the fix if anyone wants to turn me on to which specific file I'd enter those CSS changes listed above into. In the meantime, I'ma clone the repo and see if I can find it myself.
> > > Edit: Aighty. Found where to edit the themes. I'ma see what I can do about gettin' a pull request together for this one.
> > 
> > 
> > Where did you find the themes? I'm using macOS.
> 
> If you clone the repository and look in the root folder of the project, you'll find a file named `THEMES.md` that explains the theme stuff. It should make sense to anyone who's familiar with typical modern web design methods involving SCSS/SASS/yarn stuff. I'm still exploring, but I think I can get a proper patch set / pull request thrown together for this using your colors from above as a baseline starting point. I'll just adapt that to the other dark themes by eyedroppering colors out of those other themes.
> 
> Also, the `README.md` file contains some useful info about how to build a local "release" using `yarn run` commands.

How'd it go with building the custom dark theme?

**Comment by galaxy-nomad** [comment]
Thanks so much to the developer for rolling out theme fixes in the latest update!!!
