### ISSUE TITLE
If you don't trust it don't use it I know totally aware just 1 question

### ISSUE THREAD

**Issue by Jaladhjin** [jerrod-lankford/google-voice-desktop-app#129]
Hybrid-Analysis came up with this:

[The analysis extracted a file that was identified as malicious](https://www.hybrid-analysis.com/sample/ce098f93c5c6db63b9c3f1784f28d414c04688f87601755ecaa8b554626e9a5a/62da516a27290f052e42525d#signature-aef27ad69f9b85549964ece0fa8cfedd)
details
1/68 Antivirus vendors marked dropped file "SpiderBanner.dll" as malicious (classified as "Malware.Generic" with 1% detection rate)
source
Extracted File
relevance
10/10

And looking into that .dll I find a bunch of stuff like this: https://forum.obsidian.md/t/what-is-spiderbanner-dll-why-is-it-connecting-to-a-bunch-of-external-ips/17621

Are you able to explain what that .dll is doing?

Again I'm totally clear "if you don't trust it don't use it"

Just curious since Jotti & Virustotal both found 0 problems which is great.

https://www.hybrid-analysis.com/sample/ce098f93c5c6db63b9c3f1784f28d414c04688f87601755ecaa8b554626e9a5a

**Comment by pbanj** [comment]
if you read the link you posted it's explained what it is/doing

![image](https://user-images.githubusercontent.com/17306233/181381070-736f07ff-7f38-49e9-940c-37268bd70a4a.png)

**Comment by Jaladhjin** [comment]
Thank you!
