### ISSUE TITLE
Missing theme settings option

### ISSUE THREAD

**Issue by drasticweevil** [jerrod-lankford/google-voice-desktop-app#148]
According to the reddit post that led me to this app, there should be a settings icon under spam that allows me to change the theme. I do not see this. Alternatively, a dark mode, as suggested in another issue that was recently submitted would be fine.

**Comment by drasticweevil** [comment]
I did some more poking around and realized I didn't have the most updated version. After updating I still didn't see the settings in the app window, but found them by right clicking on the tray icon.

**Comment by latin-programmer** [comment]
Yeah, I mentioned this to the author of the repo when we did the change. I personally don't like changes that make options seem to "disappear". I lost the argument because it was hacky the way that we were adding the menu there so we moved to the more "standard" electron menu and tray.

**Comment by latin-programmer** [comment]
![image](https://user-images.githubusercontent.com/3208425/215348737-0ee6e337-8320-4987-83b9-5dc36d53b159.png)
Here is the new "official" location by the way.
