### ISSUE TITLE
v1.1.5 / MacOS - Force quit always required. Multiple account use at some point?

### ISSUE THREAD

**Issue by perpetualapprentice** [jerrod-lankford/google-voice-desktop-app#25]
Non-programmer observations... So nice to see this is happening!

Force quit required 100% of the time on MacOS 10.13.6. Otherwise looks good and very functional.
Is the single account limit intentional? Unsecured app warning when attempting to add a second.

**Comment by Jerrkawz** [comment]
It closes to the notification area and you quit from there. I wonder if i can override the quit for mac doc to allow this to always work.

**Comment by brmonaghan** [comment]
Agree with multiple account usage. Why not you just open another instance of this and use that? Oh, that's right, it will close it out! 🤦🏻‍♂️

**Comment by perpetualapprentice** [comment]
> It closes to the notification area and you quit from there.

Command-Q and the 'quit' menu does close the main window but app remains open until force quit. Nothing else works. Mostly a problem because it messes with end of day energy saver automatic shutdown.

**Comment by jerrod-lankford** [comment]
2fa fixed in 1.2.0, force quit bug fixed in upcoming 1.2.1

**Comment by jboolean** [comment]
It still seems that Voice Desktop doesn't respond to Quit signal either from the menu, Command-Q, or the Dock. The universal pattern on Mac is that Quit should Quit—not just close the main window. 
For applications that have a menu bar item, this is usually implemented as a separate process that can be turned on and off via a preference. Such a process usually continues to run after the main app is quit. See 1Password, Dropbox, Creative Cloud, Arq for examples.

**Comment by waltsatan** [comment]
Quit works from the menu bar item in 1.2.5, but not from File -> Quit as expected.  I, too, had to previously do the force-quit technique using 1.1.5 so I guess this is an improvement?
