### ISSUE TITLE
app being open stops big sur from rebooting for update

### ISSUE THREAD

**Issue by cbeale** [jerrod-lankford/google-voice-desktop-app#29]
found an issue last night.  had the app open.  went to update to macos big sur 11.1 RC1.  everything else was closed and the computer just sort of hung with no error message like it was still trying to close stuff and sat there for a bit.  the instant i manually closed google voice desktop app the system rebooted and started the update.  may want to add a way to handle the message for when its trying to close all the apps.

**Comment by cbeale** [comment]
updatea: still happens

**Comment by jerrod-lankford** [comment]
Fixed with ed02a9f, pending release 1.2.1
