### ISSUE TITLE
Message Pane Not updating

### ISSUE THREAD

**Issue by AceRoehrborn** [jerrod-lankford/google-voice-desktop-app#31]
This app is really super great!  Thanks for your efforts on it.

I am noticing something odd when new messages arrive.  The message arrives and the app notifies so i hear an audible notification.  The left messaging pane shows the sender and the first half a sentence or so of the message (Whatever fits in the window). 

The problem is the right pane that shows the message thread from that sender does not update and display the new message at the bottom of the thread.  Sometimes for a very long time.  This does not happen every time.  Most of the time the messages pop right in as I would expect.

I have played around to see if I could add any better info.  Sometimes clicking on a different thread and then back to the recent message will be enough to force a refresh.  Other times restarting the app completely will do it.  Sometimes just waiting 10 minutes or so will cause the message to appear.

It seems to me a refresh needs to be forced on the thread somehow.

Running the app on Windows 10 pro.  I am actually running it on a few different machines with at least two different accounts and see the same behavior on all the locations.

Thanks again for a great app.

Also... The discord link on the github main page seems to be broken.

**Comment by hendrimp1** [comment]
I am seeing the same behavior here as well on Windows 10 20H2.

**Comment by marksibert** [comment]
Same problem here on 1.1.8.  Windows 10 Enterprise.

**Comment by jerrod-lankford** [comment]
I cant really reproduce this but also since this is just a wrapper around voice.google.com I highly doubt its specific to the electron wrapper.

**Comment by marksibert** [comment]
You're right that the behavior is in voice.google.com as well.  But could you add code to force a refresh every couple minutes?

**Comment by jerrod-lankford** [comment]
Its probably not a bad idea to do this for the memory leak as well. I'll track under #61
