### ISSUE TITLE
Hiding call sidebar

### ISSUE THREAD

**Issue by skrekk19** [jerrod-lankford/google-voice-desktop-app#32]
Is there an easy way to hide the "call sidebar" (the rightmost pane of the app) without recompiling the app?    In Chrome I do this with a filter in uBlock Origin: 
voice.google.com##gv-call-sidebar

**Comment by josephrooks** [comment]
Also came here to ask this question -- the screenshots show it hidden, but it's not hidden in the Windows app.

**Comment by latin-programmer** [comment]
There is an "easy" way to hide it, just make the window smaller and it will go away. If you don't like to make the windows smaller, I'm getting close to getting #56 merged where you will be able to "zoom". This will be a way to make it go away by making it zoom more until it goes away. You can check how this works on your regular browser by changing the size of your window of the zoom of the page.

**Comment by jerrod-lankford** [comment]
Done in 1.2.8!
