### ISSUE TITLE
Windows Desktop app identifies itself as a Mac app?

### ISSUE THREAD

**Issue by jofowler** [jerrod-lankford/google-voice-desktop-app#34]
This isn't really a problem, just a question. 
Short version: Does your Windows desktop app identify itself as a Mac application?

Long version: Not long after I installed your Windows desktop app and logged in for the first time, I got a security alert from Google. The main part of it said, "Your Google Account was just signed in to from a new Mac device. You're getting this email to make sure it was you."  I don't own a Mac, so I was somewhat alarmed. Then I looked back to see what I was doing around that time and I was installing your app. Are you sending a Mac identifier in your header?

Thanks for the app. I find it very handy.

**Comment by latin-programmer** [comment]
I reviewed the code recently, it does it because of this line:
"win.loadURL('https://voice.google.com', { userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0' });" 

Whenever the app opens-up Google Voice it needs to act as a "browser" and it just happens to pick the Mac's ID on it. I've been trying to get into the discord to see if there is a better way to do it.

**Comment by DarylO71** [comment]
@latin-programmer Thank you for the explanation.  I was wondering about the same thing.  How could I modify the userAgent on this?

**Comment by latin-programmer** [comment]
@DarylO71 You would have to create your own build for it. I did look into other more "reasonable" options but it doesn't seem to be a good answer for that one. Maybe there is an argument to make it at least Windows or Linux as I would bet most of us doesn't use Mac's but then the Mac users will complain. Also, I bet all the two factor authentication will trigger for all of us if we release a new build for it and that would freak a lot of people out if they went through all that trouble.

**Comment by DarylO71** [comment]
@latin-programmer Okay.  Thanks for the reply.

**Comment by jerrod-lankford** [comment]
I removed the user agent and it uses the default electron one now. Everything still seems to function as before
