### ISSUE TITLE
Can't add another account, error: "This browser or app may not be secure."

### ISSUE THREAD

**Issue by hiroo916** [jerrod-lankford/google-voice-desktop-app#38]
I have two Google accounts with GV attached.  I would like to be able to easily switch back and forth or have them in two different tabs. 

When I click my Google user icon at the top right to add an account, it pops up a browser window to log into Google, but it gives the error "This browser or app may not be secure." Not sure how this window differs from the initial setup authentication process.  
![Screen Shot 2021-02-22 at 5 05 28 PM](https://user-images.githubusercontent.com/43597668/108790158-dce7f080-7530-11eb-8799-512dbe8f458a.JPG)
Is there any way to get two accounts enabled?

I tried making another copy of that app, but on running that, it opens up then closes and redirects to the original instance.

**Comment by jerrod-lankford** [comment]
Should be fixed with #77 in 1.2.0
