### ISSUE TITLE
Can't sign in if using multi factor authentication

### ISSUE THREAD

**Issue by adefaria** [jerrod-lankford/google-voice-desktop-app#41]
I  have MFA on my Google account. When attempting to sign in it gets to 2-Step Verification then just hangs. Can't go much further.

**Comment by rpodric** [comment]
I have it too, and the app hasn't been updated, but it worked for me. The prompt for approval comes through on your phone. Once it's approved, you're done, and you can tell the desktop app not to ask again for the device.
