### ISSUE TITLE
Calls and messages don't load

### ISSUE THREAD

**Issue by seanchito** [jerrod-lankford/google-voice-desktop-app#44]
Thanks for making this.   I've got 1.1.5 installed on W10 Home x64, but when I start the app the lists of calls and messages never populate.  It's just perma-spinning doughnut where the lists should be.  Nothing ever appears in the center column, just 'You're all caught up.'  Same for Voicemail, Archive, Spam.  I can make calls with the keypad, but there's no way to send messages, and clicking 'send new message' does nothing.    Doesn't seem like it's responding to incoming calls or messages.   It still says 'all caught up' when there is a new unread message.   Google Voice web page and iphone app work as expected.   

I'd love to get this working as Hangouts Voice integration is RIP as of today.   Any ideas?

![image](https://user-images.githubusercontent.com/81403458/113459132-864cbc80-93e2-11eb-8473-b9285a2514bf.png)

**Comment by brmonaghan** [comment]
fixed in v1.1.9

**Comment by brmonaghan** [comment]
@seanchito its right [here](https://github.com/brmonaghan/google-voice-desktop-app/releases/tag/v1.1.9)

**Comment by seanchito** [comment]
Thanks, but 1.1.9 (mis)behaves the same way on my machine.   This version works perfectly, but it's a different repo.   Not sure what the difference is.   But it doesn't minimize to the system tray, so my quest for desktop GV continues...

https://github.com/taralika/google-voice-desktop

**Comment by latin-programmer** [comment]
> Thanks, but 1.1.9 (mis)behaves the same way on my machine. This version works perfectly, but it's a different repo. Not sure what the difference is. But it doesn't minimize to the system tray, so my quest for desktop GV continues...
> 
> https://github.com/taralika/google-voice-desktop

I looked at his app. The name is the same but the app is different. It is very short as well. From looking at it, you will not have the customize menu on it. It is an interesting approach and it does have that icon with the number of messages on it that people have been requesting for this app.

**Comment by Jerrkawz** [comment]
There is no 1.1.9. @brmonaghan started his own builds for some reason but they aren't official and I cannot vouch for them so i would remain cautious. Only the builds on my repository should be used.

As for the issue with messages not loading im unsure. You could right click, inspect and look for console errors

**Comment by brmonaghan** [comment]
I started mine because of a tagging issue with my account.

**Comment by seanchito** [comment]
It's unable to load anything from google's servers.  I get the same spinning donut when I try to play my voicemail greeting, for example.  Right click gives me an 'inspect' option which is functionless.   And strangely, it knows my google account and Voice number even when I am not signed in.  Signing out of google in the app does nothing.  Uninstall and reinstall while signed out of Google, still loads my Google acct.   How is this possible?   Is there a config file I can delete somewhere?

**Comment by jerrod-lankford** [comment]
If you still have issues or still care you can try 1.2.0 and reopen if that doesnt work. Trying to clean up the issues list and tackle some bugs
