### ISSUE TITLE
Messages not transporting

### ISSUE THREAD

**Issue by GooseLake** [jerrod-lankford/google-voice-desktop-app#49]
Installed on Win10, logged in to account, all looked good with historic messages, contacts, etc. 
Attempted to send a message while also had a GV tab open to see if transport worked.
I can see the message, the intended recipient never received the message.
So I then tried to send to a group with me and the recipient, I could see sent, as well as received the message, however, the other did not.
Tried this with numerous other contacts, all the same results.

**Comment by rpodric** [comment]
I hadn't tried it with texts yet, but I just tested 1.1.6 with USPS tracking, and the message was definitely received on their end since you have to opt in and it told me that I did successfully.

**Comment by jerrod-lankford** [comment]
If theres an issue with this it would be with the voice app, not the electron wrapper
