### ISSUE TITLE
No Notification Count in Badge in Ubuntu

### ISSUE THREAD

**Issue by DarylO71** [jerrod-lankford/google-voice-desktop-app#50]
I have this Electron app installed in Ubuntu 20.04, and I noticed that the badge doesn't get updated with a notification count in GNOME Shell.  All the icon shows is a red dot.  In Cairo Dock, no badge shows at all in the dock.  Thanks for the app, by the way!

**Comment by jerrod-lankford** [comment]
I vaguely recall this as well. I dont think theres anything like osx that allows me to set a number in ubuntu. If you think otherwise then reopen
