### ISSUE TITLE
Can you add an option to exit the app by hitting the close button?

### ISSUE THREAD

**Issue by alpenandrew** [jerrod-lankford/google-voice-desktop-app#62]
This is the default behavior for windows apps

**Comment by rpodric** [comment]
Though not a default for ones designed to be "close to tray" programs like this one. Not many would want to close _close_ the program, especially accidentally.

**Comment by alpenandrew** [comment]
Hence "can you add an option"

**Comment by jerrod-lankford** [comment]
Im not sure it would be worth it. If many people tell me im wrong then we can revisit
