### ISSUE TITLE
Clicking on settings icon and returning to messages: customize button disappears, settings view themes not applying

### ISSUE THREAD

**Issue by mathsmathsmaths** [jerrod-lankford/google-voice-desktop-app#64]
Title: When clicking on settings the themes "break" but come back when I return to messages, and upon returning to messages, the customize button is gone. Very noticeable with any dark theme set, including my custom [DarkPlus](https://github.com/Jerrkawz/google-voice-desktop-app/pull/63) theme. I could fix the theme itself but I think a fix for mappings.scss would be easier.

**Comment by jerrod-lankford** [comment]
Dupe of #47
