### ISSUE TITLE
[Feature Request] Allow use of multiple GV accounts

### ISSUE THREAD

**Issue by mathsmathsmaths** [jerrod-lankford/google-voice-desktop-app#65]
What the title says. I have two personal GV numbers and currently I need to sign out of one of the accounts in order to use the other.

**Comment by eFail** [comment]
This will be fixed by the following PR, if accepted:
https://github.com/jerrod-lankford/google-voice-desktop-app/pull/77

**Comment by jerrod-lankford** [comment]
Merged.
