### ISSUE TITLE
Messages keep building in action center

### ISSUE THREAD

**Issue by brmonaghan** [jerrod-lankford/google-voice-desktop-app#68]
When sliding notifications to right, it moves them to the action center.
I want them to be removed from the action center like it was in <1.2.2.

**Comment by brmonaghan** [comment]
![building notification error](https://user-images.githubusercontent.com/71337477/122575987-3fed1e00-d01f-11eb-9523-93241bda9322.png)
This is what's going on. It keeps sending to notification center without clearing.

**Comment by reesericci** [comment]
that sounds like a windows thing, try running 1.21 and see if that fixes it.
