### ISSUE TITLE
Caller information suddenly ultra-low-contrast in dark themes

### ISSUE THREAD

**Issue by or0b0ur0s** [jerrod-lankford/google-voice-desktop-app#69]
All caller information in the leftmost panel is now unreadable unless individually highlighted when using any of the darker themes.  The text used to be high-contrast white but changed spontaneously mid-session as I was selecting a call from the list.  I can't say for sure if there is a connection, but I also first noticed 2 other issues I see posted here within a day of this one (the memory leak - it locked my machine after eating a full 20 gb memory while I was AFK - and the "customization menu vanishes after using it" bug).

**Comment by jerrod-lankford** [comment]
Should hopefully be fixed in 1.2.7. Please reopen if issue persists
