### ISSUE TITLE
consider updating the app...

### ISSUE THREAD

**Issue by dave15559546** [jerrod-lankford/google-voice-desktop-app#73]
...as the web app for google voice has since improved in performance

**Comment by brmonaghan** [comment]
See #74 for more info
@jerrod-lankford is currently at NC State getting a degree and does NOT have much time to maintain this program.
I will try to make this happen so it speeds up.

**Comment by brmonaghan** [comment]
Sent him an email

**Comment by dave15559546** [comment]
it still works pretty well anyway - let him get his degree - I'm not interested enough to learn electron sufficiently to update this thing...

**Comment by jerrod-lankford** [comment]
Lol I finished my degree 11 years ago. I just still have the email address. What do you mean by update the app? It just navigates to the website so if voice.google.com is up to date then so is the app

**Comment by brmonaghan** [comment]
By making it faster for my PC. It is VERY slow when it types messages
