### ISSUE TITLE
Click to call

### ISSUE THREAD

**Issue by VSkwidd** [jerrod-lankford/google-voice-desktop-app#75]
Trying to implement click to call functionality. Not sure if this application is currently set up to receive parameters but I've essentially tried adding the .exe to my callto>shell>open>command path, passing just the raw phone number (10 digit, no special characters). Anyone else attempted this?

**Comment by jerrod-lankford** [comment]
I haven't, but its a good idea. How is this different from #71 though? Can we consildate?

**Comment by geckonapper** [comment]
Does "closed this as completed" mean it's been implemented?  It's not working for me in Win 10.  Is there a protocol setting for this in the registry?  Thanks
