### ISSUE TITLE
Does this app use Hardware Acceleration?

### ISSUE THREAD

**Issue by sentrixcoin** [jerrod-lankford/google-voice-desktop-app#76]
Does this app use Hardware Acceleration? If it does, is there a way to turn it off? Would really appreciate it if someone could clarify. Thank you!

**Comment by jerrod-lankford** [comment]
Hardware acceleration as opposed to GPU acceleration? What are you asking specifically? I didnt change any of the default electron settings. https://www.electronjs.org/docs/tutorial/offscreen-rendering
