### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [jerrod-lankford/google-voice-desktop-app#78]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jerrod-lankford** [comment]
@JamieSlome Added a security.md with my email address, also enabled dependabot alerts so ill resolve some of those

**Comment by Haxatron** [comment]
Hi there, I was not able to contact the email listed in the SECURITY.md

You can access the report at https://huntr.dev/bounties/1e56ac67-6a41-490e-a9d3-6fe154ca3688. Only the owner of the GitHub repository can access the report

Thanks and regards.
