### ISSUE TITLE
Unable to contact email in SECURITY.md

### ISSUE THREAD

**Issue by Haxatron** [jerrod-lankford/google-voice-desktop-app#82]
[Opening a new issue since the other issue is already closed]

Hi there, I was not able to contact the email listed in the SECURITY.md

You can access the report at https://huntr.dev/bounties/1e56ac67-6a41-490e-a9d3-6fe154ca3688. Only the owner of this GitHub repository can access the report in the link above.

Thanks and regards.

**Comment by jerrod-lankford** [comment]
Thanks. Fixed with  4d9fcf

**Comment by Haxatron** [comment]
Hi there!
     Thanks for fixing the vulnerability! Could you validate the report at
https://huntr.dev/bounties/1e56ac67-6a41-490e-a9d3-6fe154ca3688/    ?

Thanks,
Axel
