### ISSUE TITLE
Install corrupted other programs?

### ISSUE THREAD

**Issue by KatherineKane** [jerrod-lankford/google-voice-desktop-app#86]
Right after I installed this desktop app, my Deluge stopped working properly. So, I rebooted the computer, and when it still wasn't working, I went into Uninstall or Change to see if the install needed repair of some kind. I found the following software installs had all been corrupted on the same day. 

Deluge 1.3.15
Discord
HttptoUsbBridge
Hypersnap 8
NVIDIA PhysX
Update for Windows 10... KB4023057

I didn't create a restore point before I installed this, and I tried rolling back to the last saved point, but that was after I'd installed the app. I have tried everything short of reinstalling Windows to fix the problem, and nothing seems to help. For example, if I uninstall, go through and make sure every folder and file is deleted, from Deluge, Discord or Hypersnap, then reinstall any of them, the new installation still shows it as corrupted and it gives me errors if I try to open the software (Deluge won't reopen at all). 

Any ideas how I can roll back whatever this app did to fix the problem. It was a very useful app for a few days, when my phone was broken and I had to have my calls forwarded to my Google Voice line. But now I just need to get this resolved as quickly as possible - I'm behind on my school work from all the stuff going on lately, and I don't have time to setup my PC back up the way I prefer it, right now. 

Thanks for any input  you can offer.

**Comment by Techwizz-somboo** [comment]
All I can say is it's most likely coincidence that those programs broke and nothing related to this project. You could have a virus of some kind on your computer though that's unrelated and got triggered for whatever reason. Try doing virus scans, and perhaps scan with malwarebytes as well. Sorry to hear things broke for you!
