### ISSUE TITLE
Can't copy and paste anymore

### ISSUE THREAD

**Issue by manishie** [jerrod-lankford/google-voice-desktop-app#91]
Hi, after installing 1.2.6 on macos big sur 11.2.3, I can no longer copy/paste anywhere in the app (in a text message, search box, name/phone number field, etc.)

**Comment by FormallyKnownAs** [comment]
I've noticed this as well. The workaround for me is to highlight the text you want to copy, right-click and select copy.  Not an idea solution but seems to work

**Comment by jerrod-lankford** [comment]
Turns out this was broken with the addition of the Application bar, we needed to add an edit menu and do the proper key bindings. Fixed in 1.2.8

**Comment by manishie** [comment]
Works great, thank you!
