### ISSUE TITLE
Won't allow me to sign in, claims insecure browser.

### ISSUE THREAD

**Issue by msheppard84** [jerrod-lankford/google-voice-desktop-app#92]
https://i.imgur.com/hbyovOJ.png

**Comment by jasoncollege24** [comment]
I have the same problem. Win10 21H2

**Comment by eubben** [comment]
and I make 3. MacOS Monterey 12.0.1, not an OS specific issue apparently

**Comment by jasoncollege24** [comment]
In my case, it seems to have fixed itself. Could've been an issue on Google's part. I'm using 2-step verification, with no app passwords. I'd suggest other users try again, with a fresh install.

**Comment by msheppard84** [comment]
@jasoncollege24 Same, just tried again and it appears to be fixed.

**Comment by typer139** [comment]
I am getting this error and it looks like it might be the 2-step Verification that's causing it.  Not sure how to work around that, other than possibly disabling 2-Step, which isn't ideal.

**Comment by jasoncollege24** [comment]
2-step shouldn't be the issue. I set it up just the other day with 2-step verification on, and it works fine.
