### ISSUE TITLE
Anyone seeing it silently close (crash) after a few days of continuous use?

### ISSUE THREAD

**Issue by rpodric** [jerrod-lankford/google-voice-desktop-app#93]
I don't think this happened before 1.2.6, but after a few days (no reboots in the interim) I'll look to the tray and it'll be gone. It's no longer running, and it doesn't happen from user action, either ("Exit application..." is unchecked).

There's no record of an appcrash in Event Viewer, however, which may or may not be normal for an Electron app. Is any record of this kept among its own files, perhaps? A log? If so, I'll post it here.

Win11/1.2.6

**Comment by dave15559546** [comment]
I am seeing this - I just have a little script to kill it and restart it

**Comment by rpodric** [comment]
Oh, you mean as a kind of prophylactic. I wish there were a clean way to exit apps with tray icons though like this one (I've attempted this before with something else for another reason but never found a solution). I'm afraid when you kill it you end up with a ghost tray icon. Yes, it's easily dismissed by swiping the mouse over it, but still.

**Comment by dave15559546** [comment]
i just run the script as needed and then hover my mouse over to kill the extra icon

that said, i'm tempted to move back to an earlier less flakey version despite the nice added feature of a flashing taskbar icon

sometimes i'm even tempted to switch over to imessage and then configure a mac vm for computer access to texts/etc. but that seems even more headache inducing...

shame everyone can't just use one GOOD standard...

**Comment by rpodric** [comment]
Will test with the new version out today, though I should say, like a watched pot waiting to boil, I haven't seen the problem in the last week. I have no explanation.

In addition to what's mentioned in the release notes, it's possible the version of Electron was updated, too, though I don't know how to see what version of Electron we're on then or now.

**Comment by jerrod-lankford** [comment]
Please reopen if issue persists pass 1.2.7
